<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Psy\Util\Str;

class User extends Authenticatable
{
    // Notifiable 是消息通知相关的引用
    // HasFactory 是模型工厂相关功能的引用
    // Authenticatable 是授权相关功能的引用
    use HasFactory, Notifiable;

    /**
     * 指定需要交互的数据表名称
     * @var string
     */
    protected $table = "users";

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * 获取用户头像
     * @param int $size
     * @return string
     */
    public function gravatar($size = 100)
    {
        $hash = md5(strtolower(trim($this->attributes['email'])));
        return "http://www.gravatar.com/avatar/$hash?s=$size";
    }

    /**
     * 定义监听器
     * boot 方法会在用户模型类完成初始化之后进行加载
     */
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // created 用于监听模型被创建之后的事件
        // creating 用于监听模型被创建之前的事件
        static::creating(function ($user) {
            $user->activation_token = \Illuminate\Support\Str::random();
        });
    }
}
